### ISSUE TITLE
Roadmap RL Zoo

### ISSUE THREAD

**Issue by araffin** [DLR-RM/rl-baselines3-zoo#299]
New env support:
- [ ] Isaac Gym
- [ ] Env Pool (https://github.com/DLR-RM/rl-baselines3-zoo/issues/241)
- [ ] Brax envs

Improvements:
- [ ] Allow to save stats with checkpoints / best model stats (https://github.com/DLR-RM/rl-baselines3-zoo/issues/278)
- [ ] Improve test coverage
- [ ] Add low pass filter wrapper (https://github.com/ikostrikov/walk_in_the_park/blob/ee345db217f9d7392963a76c93dc186474075f80/filter.py)
- [ ] Improve hyperparameter optimization + stand alone (as for cleanrl): (https://github.com/DLR-RM/rl-baselines3-zoo/issues/121)
