### ISSUE TITLE
[Bug]: TODO: add test dependencies in the `setup.py`

### ISSUE THREAD

**Issue by power-edge** [DLR-RM/rl-baselines3-zoo#435]
### 🐛 Bug

There is a note in the setup.py
> TODO: add test dependencies

And some tests will fail based on missing dependencies after install.

### To Reproduce

```shell
./scripts/run_tests.sh
```
and to reproduce failed tests

# test_benchmark
```shell
export N_STEPS=100
export BENCHMARK_DIR=/tmp/benchmark-$(date +%s)
mkdir $BENCHMARK_DIR
python -m rl_zoo3.benchmark -n "${N_STEPS}" --benchmark-dir "${BENCHMARK_DIR}" --test-mode --no-hub
```

### Relevant log output / Error message

```shell
04:29:21 (venv) nik@nik-ThinkPad-P1-Gen-2 rl-baselines3-zoo ±|dev ✗|→ python -m pytest --cov-config .coveragerc --cov-report html --cov-report term --cov=. -v -m "not slow" --color=yes
=============================================================================================================================================================================================================================== test session starts ================================================================================================================================================================================================================================
platform linux -- Python 3.10.12, pytest-8.0.1, pluggy-1.4.0 -- /home/nik/code/power-edge/rl-baselines3-zoo/venv/bin/python
cachedir: .pytest_cache
rootdir: /home/nik/code/power-edge/rl-baselines3-zoo
configfile: pyproject.toml
plugins: xdist-3.5.0, env-1.1.3, cov-4.1.0
collected 262 items / 192 deselected / 70 selected                                                                                                                                                                                                                                                                                                                                                                                                                                 

tests/test_callbacks.py::test_raw_stat_callback PASSED                                                                                                                                                                                                                                                                                                                                                                                                                       [  1%]
tests/test_enjoy.py::test_benchmark FAILED
...


# for `test_benchmark` the output is 

ModuleNotFoundError: No module named 'pytablewriter'
```


### System Info

_No response_

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/rl-baselines3-zoo/issues) in the repo
- [X] I have read the [SB3 documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have read the [RL Zoo documentation](https://rl-baselines3-zoo.readthedocs.io)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> ModuleNotFoundError: No module named 'pytablewriter'

That's weird, `pytablewriter` is listed as dependency

https://github.com/DLR-RM/rl-baselines3-zoo/blob/8cecab429726d7e6aaebd261d26ed8fc23b7d948/setup.py#L37

btw, for the full tests, `-r requirements.txt` is needed.
